language: php

php:
    - 5.3
    - 5.4

env:
    global:
    - secure: Woh7BmZy1g4G0NzgD405bko4/83jQiXzbiuOnwJD2BaMpG8JYjR5eb9AS3XhlH+ySZKOYm6i9Btz+uVuKAGZqNgr/gnQytWeY7UL1X74IfemuPlDS6W5eQAZ3NgfQAN50DE5kB9BfpEMIdlifM2GtYmkX+j+3k0KfG1bjwvK5yI=
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

before_script:
    - export REPO_BASE=`pwd`
    - export PLUGIN_SLUG=$(basename $REPO_BASE)
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit

after_success:
     - bash bin/travis_onSuccess.sh
